#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     magnetic,            sensorHiTechnicMagnetic)
#pragma config(Sensor, S4,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {

	  if(SensorValue[IR] < 3)
	  {
	    motor[motorD] = 40;
	    motor[motorE] = -40;
	  }
	  else if (SensorValue[IR] > 3 && SensorValue[IR] < 5)
	  {
	    motor[motorD] = 40;
	    motor[motorE] = -40;
	  }
	  else if (SensorValue[IR] > 7)
	  {
	    motor[motorD] = -40;
	    motor[motorE] = 40;
	  }
	  else if (SensorValue[IR] > 5 && SensorValue[IR] < 7)
	  {
	    motor[motorD] = -40;
	    motor[motorE] = 40;
	  }
	  else if (SensorValue[IR] > 4 &&   SensorValue[IR] < 6)
	  {
	    motor[motorD] = 20;
	    motor[motorE] = 20;
	  }


	  nxtDisplayTextLine(5, "Value is : %4d" + SensorValue[IR]);
	}
}
