#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Mag,                 sensorHiTechnicMagnetic)
#pragma config(Sensor, S4,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

task ejecta()
{
  while(true)
  {
  motor[motorD] = -100;
  wait1Msec(5000);
  motor[motorD] = 0;
  wait1Msec(100);
  wait1Msec(10);
  }
}

task ejectb()
{
  while(true)
  {
  motor[motorA] = 100;
  wait1Msec(7000);
  motor[motorA] = 0;
  wait1Msec(1000);
  wait1Msec(10);
  }
}
task main()
{
  int threshold = 10;
  while(true)
  {
 getJoystickSettings(joystick);

    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorE] = joystick.joy1_y2/1.5;
    }
    else
    {
      motor[motorE] = 0;
    }

    StartTask(ejecta);
  StartTask(ejectb);
  }
}
