#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S3,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
int x;

task main{
  /*
  while (true)
  {
  if (SensorValue[IR] < 3)
  {
    motor[motorD] = -40;
    motor[motorE] = 40;
  }
  else if (SensorValue[IR] > 3 && SensorValue[IR] < 5)
  {
    motor[motorD] = -40;
    motor[motorE] = 40;
  }
  else if (SensorValue[IR] > 7)
  {
    motor[motorD] = 40;
    motor[motorE] = -40;
  }
  else if (SensorValue[IR] > 5 && SensorValue[IR] < 7)
  {
    motor[motorD] = 40;
    motor[motorE] = -40;
  }
  else if (SensorValue[IR] > 4 &&   SensorValue[IR] < 6)
  {
    motor[motorD] = 20;
    motor[motorE] = 20;
  }


  nxtDisplayTextLine(5, "Value is : %4d" + SensorValue[IR]);
  }*/
if(joy1Btn(9) == 1)
    {
      //servo[servo3] = 225;
      servo[servo5] = 200;
    }
    else if (joy1Btn(10) == 1)
    {
      //servo[servo3] = 100;
      servo[servo5] = 155;
    }
}
