#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     magnet,              sensorHiTechnicMagnetic)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//October 14, 2011
//Claw mechanism in front works
//Magnet claw mechanism works
//Back hatch servos work, need to adjust motor, and see if 2 stack can be created

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



task main()
{


  int threshold = 10;

  while (true)
  {
    nxtDisplayTextLine(3, "Value is : %4d" + nImmediateBatteryLevel);
    nxtDisplayTextLine(2, "Value is : %4d" + externalBatteryAvg);
    nxtDisplayTextLine(5, "Value is : %4d" + SensorValue[magnet]);

    /*if (nImmediateBatteryLevel < 8000 && externalBatteryAvg < 14000)
    {
      PlayTone(100, 5);
    }

    else if (externalBatteryAvg < 14000 && nImmediateBatteryLevel > 8000)
    {
      PlayTone(500, 5);
    }

    else if (externalBatteryAvg > 14000 && nImmediateBatteryLevel < 8000)
    {
      PlayTone(900, 5);
    }*/

    //battery level check

    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorE] = joystick.joy1_y2/1.5;
    }
    else
    {
      motor[motorE] = 0;
    }


    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorD] = joystick.joy1_y1/1.5;

    }
    else
    {
      motor[motorD] = 0;
    }

    if(SensorValue[magnet] < 665  && SensorValue[magnet] > 653)  //Magnetic servo stopper
    {
      servo[servo1] = 100;
    }

    else
    {
      servo[servo1] = 255;
    }

    if(joy1Btn(1) == 1)         //NXT servo magnetic scorer
    {
      motor[motorB] = 20;
    }
    if(joy1Btn(2) == 1)
    {
      motor[motorB] = -20;
    }
    if(joy1Btn(1) == 0 && joy1Btn(2) == 0)
    {
      motor[motorB] = 0;
    }
    if(joy1Btn(5) == 1)
    {
      motor[motorA] = 95;
    }
    else if (joy1Btn(6) == 1)
    {
      motor[motorA] = -20;
    }
    else
    {
      motor[motorA] = 0;
    }
    if(joy1Btn(7) == 1)
    {
      servo[servo4] = 140;
    }
    else if (joy1Btn(8)== 1)
    {
      servo[servo4] = 0;
    }
    if(joy1Btn(9) == 1)
    {
      servo[servo3] = 225;
    }
    else if (joy1Btn(10) == 1)
    {
      servo[servo3] = 100;
    }
    if(joy1Btn(3) == 1)
    {
      motor[motorC] = 7;
    }
    else if(joy1Btn(4) == 1)
    {
      motor[motorC] = -7;
    }
    else
    {
      motor[motorC] = 0;
    }









  }
}
