#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     magnetic,            sensorHiTechnicMagnetic)
#pragma config(Sensor, S4,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////5///////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
task a()
{
  /*if(joystick.joy1_TopHat == 0)
  {
    motor[motorA] = 0;
  }
  else
  {*/
    motor[motorA] = -100;

}

task b()
{/*
  if(joystick.joy1_TopHat == 0)
  {
    motor[motorG] = 0;
  }
  else
  {*/
    motor[motorG] = 100;

}


task main()
{

  initializeRobot();
  int threshold = 7;
  waitForStart();   // wait for start of tele-op phase
  servo[servo1] = 0;
  servo[servo2] = 255;
  servo[servo3] = 70;
  wait1Msec(1000);

  while(true)
  {
    nxtDisplayTextLine(5, "%4d" + SensorValue[magnetic]);
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorD] = joystick.joy1_y2/2;
    }
    else
    {
      motor[motorD] = 0;
    }


    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorE] = joystick.joy1_y1/2;

    }
    else
    {
      motor[motorE] = 0;
    }
    if(joy1Btn(1) == 1)
    {
      motor[motorA] = 0;
      wait1Msec(100);
      motor[motorA] = 100;
      wait1Msec(1000);
    }

    if(joy1Btn(2) == 1)
    {
      motor[motorH] = 40;
      motor[motorI] = 40;
    }
    else if (joy1Btn(3) == 1)
    {
      motor[motorH] = -30;
      motor[motorI] = -30;
    }
    else
    {
      motor[motorH] = 0;
      motor[motorI] = 0;
    }


    if(joy1Btn(5) == 1)
    {
      servo[servo1] = 0;
      servo[servo2] = 255;
      wait1Msec(1000);
    }
    if(joy1Btn(6) == 1)
    {
      servo[servo1] = 255;
      servo[servo2] = 0;
      wait1Msec(1000);
    }
    if(joy1Btn(7)  == 1)
    {
      servo[servo3] = 200;
      wait1Msec(500);

    }
    if(joy1Btn(8)  == 1)
    {
      servo[servo3] = 60;
      wait1Msec(500);
    }
    /*if(SensorValue[magnetic] < 654 || SensorValue[magnetic] > 660)
    {
      nMotorEncoder[motorB] = 0;
      while (nMotorEncoder[motorB] < 90)
      {
        motor[motorB] = 5;
      }
      motor[motorB] = 0;
      wait1Msec(5000);
      while (nMotorEncoder[motorB] > 0)
      {
        motor[motorB] = -5;
      }
      motor[motorB] = 0;

    }*/
  StartTask(a);
  StartTask(b);
}
}
