#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task a()
{
  motor[motorA] = -100;
}

task b()
{
  motor[motorG] = 100;
}
int threshold = 7;
task main()
{
  while(true)
  {
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorD] = joystick.joy1_y2/1.5;
    }
    else
    {
      motor[motorD] = 0;
    }


    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorE] = joystick.joy1_y1/1.5;

    }
    else
    {
      motor[motorE] = 0;
    }
    if(joy1Btn(1) == 1)
    {
      motor[motorA] = 0;
      wait1Msec(100);
      motor[motorA] = 100;
      wait1Msec(1000);
    }
  StartTask(a);
  StartTask(b);
}
}
