#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S2,     magnetic,            sensorHiTechnicMagnetic)
#pragma config(Sensor, S4,     IR,                  sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"



task a()
{
  /*if(joystick.joy1_TopHat == 0)
  {
    motor[motorA] = 0;
  }
  else
  {*/
    motor[motorA] = -100;

}

task b()
{/*
  if(joystick.joy1_TopHat == 0)
  {
    motor[motorG] = 0;
  }
  else
  {*/
    motor[motorG] = 100;

}


int threshold = 7;
task main()
{

  servo[servo1] = 0;
  servo[servo2] = 255;
  servo[servo3] = 70;
  wait1Msec(1000);

  while(true)
  {
    nxtDisplayTextLine(5, "%4d" + SensorValue[magnetic]);
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorD] = joystick.joy1_y2/2;
    }
    else
    {
      motor[motorD] = 0;
    }


    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorE] = joystick.joy1_y1/2;

    }
    else
    {
      motor[motorE] = 0;
    }
    if(joy1Btn(1) == 1)
    {
      motor[motorA] = 0;
      wait1Msec(100);
      motor[motorA] = 100;
      wait1Msec(1000);
    }

    if(joy1Btn(2) == 1)
    {
      motor[motorH] = 40;
      motor[motorI] = 40;
    }
    else if (joy1Btn(3) == 1)
    {
      motor[motorH] = -30;
      motor[motorI] = -30;
    }
    else
    {
      motor[motorH] = 0;
      motor[motorI] = 0;
    }


    if(joy1Btn(5) == 1)
    {
      servo[servo1] = 0;
      servo[servo2] = 255;
      wait1Msec(1000);
    }
    if(joy1Btn(6) == 1)
    {
      servo[servo1] = 255;
      servo[servo2] = 0;
      wait1Msec(1000);
    }
    if(joy1Btn(7)  == 1)
    {
      servo[servo3] = 200;
      wait1Msec(500);

    }
    if(joy1Btn(8)  == 1)
    {
      servo[servo3] = 60;
      wait1Msec(500);
    }
    /*if(SensorValue[magnetic] < 654 || SensorValue[magnetic] > 660)
    {
      nMotorEncoder[motorB] = 0;
      while (nMotorEncoder[motorB] < 90)
      {
        motor[motorB] = 5;
      }
      motor[motorB] = 0;
      wait1Msec(5000);
      while (nMotorEncoder[motorB] > 0)
      {
        motor[motorB] = -5;
      }
      motor[motorB] = 0;

    }*/
  StartTask(a);
  StartTask(b);
}
}
